language: python
python:
    - "3.5"
    - "3.6"
    - "pypy3"
sudo: false

before_script:
    - make install PY_BIN="python" PIP="pip"

script:
    - cd app && ./functional-test.sh
    - cd ../ && make unit_test coverage

after_success:
    - bash <(curl -s https://codecov.io/bash) -cF python

deploy:
    skip_cleanup: true
    skip_existing: true
    provider: pypi
    distributions: sdist bdist_wheel
    on:
        all_branches: true
        condition: $TRAVIS_TAG =~ ^v[0-9\.a-z\-]+ || $TRAVIS_BRANCH == "master"

    user: marek_man
    password:
        secure: jVQvdHqtkrL1smrJl/QC3YjP7vXSQ0XGuXe6nKeO0y3hDqGF8uP1FWNE4N+qSd1hJa23bN26gJa0FwrbP/n0XH82638QWw/Lu7gO5ITsoFrD3eERHqlRJ+xjsLo5NCP5/oo1fgMxWJ2Dp9xQvVRoYOc+xyyfoyllyMQY7vrpV9BZexJh9hZC2feX6B6PxmDYOV6EPnM2Nxi37kvUva7vAxJPZXrK29gJuB9VR1ToST6/ivA8LZXrjt1K/W1O8ewENr+PkDfmo8+ULHQtMEZO4/I4IvFRiLVYfCDFsJfUTkxeeMu468ZHnYyEUWcK//18UAz7bQXTOCeZbSla+g/LtBLXOo8w+V1Ws541ulJkKrekbvJB1GPwzOcVDHb9UEXtGyr8MvTkKqJUBsZFXGW3F7ClNyMvlbdf/8RDbI2xhwS402TD4e4g9cvZCy4QOGDHaAH0NldoLHdxfNQALIXrjI9HNm1bG5LQtvJ9bEsVsxcm1Zu9nSKqUfDxG12OIpAcdAwa0AoKOwds8BfIskyvbR+n37ftv6Hyv9H3ErpZh6L04y/LJeSE87+nQYwfFhZPx4KD+/D4lqCm1a98mDUwSIhkfrhF2Gvt0B0aOKP1pxGQMW8QVicOplCfdk4SHQL8J/Gy6xZbOFH7rWdDnnO/CWmlZ3UnCJDWiGssBJwstyA=

notifications:
    webhooks:
        urls:
            secure: hZR2VIgQKxNVr4WmkBP22u4wHD/azwKgXoFqlNQVTtsS14lVbaBH00Iv+Pbh2vf5KJx9+gZe0rCuEs+KEWcbd7u4I05qZT2KTphsUdkDAJyw69OIzLl1gszMgpT1StL9q8vb/pK129MDD9ytQ0a/brOVQWlJTCcbiyG08TsVxCWJQdrUkMSEwwBJgFfaZd+gd+Dm6aAqBvNBJCvF0w2PsrvtbnGTaO6duqgjxeWQ9QgwdNWA5HzqE/sjgzf5yz0bBiaRL6gpvN5P253C/Wsx7kWSsjy6sXaXaAShwNHBVaWs2DMqYUJAKPWRSipoPLWQFKMV+TaIufVhK4LnjnVIRIIHBo+mccjOSkUlwdi/tuVX3vAyLcznXIRIoVlzG4RKDYUqJNsBdbcg89aQQGtiElLgYkgUDKoSPzvRLLNcuTgQP6dZds9TmG7n+RfBSXGgzqVWpulIPfQVwUGJrkjuVemyYrkm+LLoTV6KJnuVk4YF1iIBaVqggREr7yZXkR+NgjrdZpQAFIxaE/PyQRnA86cjwyWyE5bT9I8V28nKRNACh/rRSMQcFM2z7aY72o8CVCAo2Jttw9TbpLguKkC6kkXHDyGaDSwocIoRNzSFxu2tLf+EgGKYv3agws334NICwpNx1Ri/+hA9eQJTcLIOjxKR4+iK8gbexUM6tvn+vT4=
