name: Test and release a package
on: [push]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: "pip install -r ./requirements-dev.txt && sudo apt-get install whois"

            - name: Install project via setuptools
              run: "rkd :install"

            - name: Run unit tests
              run: "rkd :test:unit"

            - name: Run functional tests
              run: "rkd :test:functional"

    release:
        needs: [build]
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: "pip install -r ./requirements.txt && pip install -r ./requirements-dev.txt && sudo apt-get install whois sshpass"

            #- name: Release to docker registry
            #  run: "rkd :release"
